version: "3.2"
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}

  api:
    image: node:latest
    container_name: api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      -  ./back_end:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev" 
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: "5"

  front:
    image: node:latest
    container_name: front
    restart: always
    env_file:
      - .env
    ports:
     - 8080:8080
    volumes:
      - ./front_end:/usr/src/front
      - /usr/src/front/node_modules
    working_dir: /usr/src/front
    command: bash -c "npm install && npm start"